---
title: "Logboek"
author: "Larissa, Marian, Sven"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

Stappen:

Quality control

Trimming

Taxonomic classification

Functional annotation

Basecalling

Visualisation

Tools:

NanoQC v.0.9.4.

NanoFilt v.2.8.0.

Kraken2 v.2.1.2.

bioBakery

Quality control & Trimming using Nanopack

Voor de quality control en het trimmen van de reads zijn de tools NanoQC en NanoFilt tools gebruikt afkomstig van NanoPack. NanoPack bevat tools geschikt voor NanoPore data.

NanoQC is gebruikt om quality reports te genereren om op basis daarvan de reads te gaan trimmen. De NanoQC reports toonden aan dat de eerste 40 baseparen en de laatste 20 baseparen zeer slecht scoorden. Om deze reden is ervoor gekozen om met headcrop en tailcrop deze baseparen te verwijderen. Verder is er een minimum Phred score ingesteld van 15.Hiervoor is de volgende shell command gebruikt:

NanoFilt --headcrop 40 --tailcrop 20 --quality 15 {input} > {output}'

Taxonomic classification using Kraken2

Voor het identificeren van de micro-organismen is de Kraken2 pipeline gebruikt. Deze pipeline is gekozen omdat de pipeline voor de classificatie zelf mapping uitvoert en het een database bevatte met referentie genomen voor zowel archaea als bacteriën. Ook genereert Kraken2 reports die als input kunnen worden gebruikt voor verschillende visualisatie tools.Hiervoor is de volgende command line gebruikt:

kraken2 --db /data/datasets/KRAKEN2_INDEX/k2_standard_20231009/ --report {log} --output {output} {input}

Functional profiling

Voor de functional profiling van de micro-organismen is gebruikt gemaakt van de HUMAnN pipeline van bioBakery. Deze pipeline is gekozen omdat ook hier al mapping plaats vind en omdat de

Basecalling

Visualisation

README

Nanoplot dowload
